In [1]:
# array #

# Array elements are stored in contiguous memory locations 
# >>> adding or removing elements requires shifting elements, O(n)

twod = [[1,2],
         [3,4],
         [5,6]]
print(twod)

for element in twod:
    print(element)

twod.append(10)
for element in twod:
    print(element)

[[1, 2], [3, 4], [5, 6]]
[1, 2]
[3, 4]
[5, 6]
[1, 2]
[3, 4]
[5, 6]
10


In [4]:
import numpy as np

twod = np.array(twod)
print(twod.ndim)
print(len(twod)) # n of rows
print(twod.size)

1
4
4


array([0, 2, 4, 6, 8])

In [6]:
np.__version__
np?

array([0, 2, 4, 6, 8])

In [28]:
## 1. creating arrays
np.array([1, 2, 3])       # 1D array
np.array([[1, 2], [3, 4]]) # 2D array
np.zeros((2, 3))          # 2x3 matrix of zeros
np.ones((3, 3))           # 3x3 matrix of ones
np.full((2, 2), 7)        # 2x2 matrix filled with 7
np.eye(3)                 # 3x3 Identity matrix
np.linspace(0, 10, 5)     # 5 equally spaced values between 0 and 10
np.arange(0, 10, 2)       # Sequence from 0 to 8 with step 2

In [ ]:
## 2. random numbers
np.random.rand(3, 3)        # 3x3 matrix of uniform random numbers [0,1)
np.random.randn(3, 3)       # 3x3 matrix of standard normal numbers
np.random.randint(0, 10, 5) # 5 random integers from 0 to 9
np.random.seed(42)          # Set seed for reproducibility

In [ ]:
# struct _longobject {
#     long ob_refcnt;
#     PyTypeObject *ob_type;
#     size_t ob_size;
#     long ob_digit[1];
# };
# A single integer in Python 3.4 actually contains four pieces:

# ob_refcnt, a reference count that helps Python silently handle memory allocation and deallocation
# ob_type, which encodes the type of the variable
# ob_size, which specifies the size of the following data members
# ob_digit, which contains the actual integer value that we expect the Python variable to represent.

np.array([range(i, i+3) for i in [2,4,6]])

In [ ]:
## 3. array operations 

A = np.array([[1, 2], [3, 4]])
B = np.array([[5, 6], [7, 8]])

A + B   # Element-wise addition
A - B   # Element-wise subtraction
A * B   # Element-wise multiplication
A @ B   # Matrix multiplication (or np.dot(A, B))
A / B   # Element-wise division
A ** 2  # Element-wise exponentiation
np.sqrt(A) # Square root

In [33]:
# 4. aggregation functions
A.sum()         # Sum of all elements
A.mean()        # Mean
A.std()         # Standard deviation
A.min()         # Minimum
A.max()         # Maximum
A.argmin()      # Index of minimum value
A.argmax()      # Index of maximum value
np.median(A)    # Median
np.percentile(A, 75)  # 75th percentile

array([[2, 2, 2, 2, 2],
       [2, 2, 2, 2, 2],
       [2, 2, 2, 2, 2]])

In [7]:
# 5. indexing & slicing 
A[0, 1]     # Element at row 0, col 1
A[:, 0]     # First column
A[0, :]     # First row
A[1, 1] = 99 # Change element at row 1, col 1
A[0:2, 0:2] # Sub-matrix (first 2 rows, first 2 cols)

NameError: name 'A' is not defined

In [36]:
# 6. Reshaping & concatenation
A.reshape(4, 1)       # Reshape to 4x1
np.hstack([A, B])     # Horizontal stacking
np.vstack([A, B])     # Vertical stacking
A.flatten()           # Convert to 1D array
np.transpose(A)       # Transpose


array([0.        , 0.11111111, 0.22222222, 0.33333333, 0.44444444,
       0.55555556, 0.66666667, 0.77777778, 0.88888889, 1.        ])

In [37]:
# 7. logical operations
A > 2      # Boolean mask
A[A > 2]   # Filtering
np.where(A > 2, 1, 0)  # Replace values based on condition

array([[-0.37681109,  0.0083433 ,  0.52476777],
       [ 0.62297525, -1.36341664, -0.5659417 ],
       [-1.03190522,  0.30221427, -0.93399073]])

In [38]:
# 8. saving & loading data
np.save("array.npy", A)    # Save array
np.load("array.npy")        # Load array
np.savetxt("array.csv", A, delimiter=",")  # Save as CSV
np.loadtxt("array.csv", delimiter=",")     # Load CSV

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [59]:
list1.sort() # ascending order 
list1
list1.sort(reverse=True)
list1
len(list1)

3

In [61]:
people = [{'name': 'Alice', 'age': 25}, {'name': 'Bob', 'age': 20}]
sorted_people = sorted(people, key=lambda x: x['age']) # lambda us anonymous(inline) funciton argments:expression
sorted_people

[{'name': 'Bob', 'age': 20}, {'name': 'Alice', 'age': 25}]

In [65]:
np.random.seed(0)  # seed for reproducibility

x1 = np.random.randint(10, size=6)  # One-dimensional array
x2 = np.random.randint(10, size=(3, 4))  # Two-dimensional array
x3 = np.random.randint(10, size=(3, 4, 5))  # Three-dimensional array
print("x3 ndim: ", x3.ndim)
print("x3 shape:", x3.shape)
print("x3 size: ", x3.size)

x3 ndim:  3
x3 shape: (3, 4, 5)
x3 size:  60


In [71]:
print(x3)
print("dtype:",x3.dtype) # int32 >>> 32 bits are used to store the integer value
print("itemsize:",x3.itemsize,"bytes") # 1 byte=8 bits, 32 bits/8= 4 bytes for each element
print("totalbytes:",x3.nbytes,"bytes")

[[[8 1 5 9 8]
  [9 4 3 0 3]
  [5 0 2 3 8]
  [1 3 3 3 7]]

 [[0 1 9 9 0]
  [4 7 3 2 7]
  [2 0 0 4 5]
  [5 6 8 4 1]]

 [[4 9 8 1 1]
  [7 9 9 3 6]
  [7 2 0 3 5]
  [9 4 4 6 4]]]
dtype: int32
itemsize: 4 bytes
totalbytes: 240 bytes


In [79]:
x1  # x[start:stop:step]
range(10)
for num in range(10):
    print(num)

0
1
2
3
4
5
6
7
8
9


In [81]:
np.random.seed(0)

def compute_reciprocals(x):
    output = np.empty(len(x))
    for i in range(len(x)):
        output[i] = 1/x[i]
    return output

x = np.random.randint(1,10,size=10)
compute_reciprocals(x)

array([0.16666667, 1.        , 0.25      , 0.25      , 0.125     ,
       0.25      , 0.16666667, 0.33333333, 0.2       , 0.125     ])

In [82]:
big_array = np.random.randint(1, 100, size=1000000)
%timeit compute_reciprocals(big_array)

346 ms ± 19.2 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)


In [84]:
%timeit (1/big_array) # 100 loops already can provide a stable estimate

3.2 ms ± 161 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)


In [90]:
print(np.arange(1,6)) # np.arrange(start[default=0], stop (exclusive, not included),step)
print(np.arange(1,11,2))

[1 2 3 4 5]
[1 3 5 7 9]


In [93]:
theta = np.linspace(0, np.pi, 3)
print(theta)
type(theta)

[0.         1.57079633 3.14159265]


numpy.ndarray

In [94]:
print("sin(theta) = ", np.sin(theta))
print("cos(theta) = ", np.cos(theta))
print("tan(theta) = ", np.tan(theta))

sin(theta) =  [0.0000000e+00 1.0000000e+00 1.2246468e-16]
cos(theta) =  [ 1.000000e+00  6.123234e-17 -1.000000e+00]
tan(theta) =  [ 0.00000000e+00  1.63312394e+16 -1.22464680e-16]


In [100]:
x = np.array([1, 2, 3])
type(x)
x**2

array([1, 4, 9])

In [101]:
from scipy import special
# Gamma functions (generalized factorials) and related functions
x = [1, 5, 10]
print("gamma(x)     =", special.gamma(x))
print("ln|gamma(x)| =", special.gammaln(x))
print("beta(x, 2)   =", special.beta(x, 2))

# Error function (integral of Gaussian)
# its complement, and its inverse
x = np.array([0, 0.3, 0.7, 1.0])
print("erf(x)  =", special.erf(x))
print("erfc(x) =", special.erfc(x))
print("erfinv(x) =", special.erfinv(x))

gamma(x)     = [1.0000e+00 2.4000e+01 3.6288e+05]
ln|gamma(x)| = [ 0.          3.17805383 12.80182748]
beta(x, 2)   = [0.5        0.03333333 0.00909091]
erf(x)  = [0.         0.32862676 0.67780119 0.84270079]
erfc(x) = [1.         0.67137324 0.32219881 0.15729921]
erfinv(x) = [0.         0.27246271 0.73286908        inf]
